version: "3"
services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "19003:19003"
      - "19004:19004"
      - "19005:19005"
      - "19006:19006"
    environment:
      NODE_ENV: local #local or prod
      TZ: "America/Denver"
    expose:
      - 19000
      - 19001
      - 19002
      - 19003
      - 19004
      - 19005
      - 19006
